import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createInitialState, renderArrangement } from "../web/lib/engine.mjs";
import { encodeMidiFile } from "../web/lib/midi-file.mjs";

const artifactDir = process.argv[2] ?? process.env.RADIO_ARTIFACT_DIR;
if (!artifactDir) {
  throw new Error("Artifact directory required");
}

await mkdir(artifactDir, { recursive: true });

const demos = [
  {
    title: "Radio Polymetric Demo",
    basename: "radio-polymetric-demo",
    state: createInitialState({
      seed: "radio-demo",
      patternCount: 8,
      startOnlyCount: 8,
      pulseCount: 0,
      meterStart: 1,
      meterCount: 8,
      baseBpm: 127,
      baseMeter: 1,
      cycleLengthKind: "bars",
      cycleLength: 4,
      basisPolicy: "next",
      replacementCadence: "one-per-bar",
      meterTiming: "same-pulse-polymeter"
    }),
    sections: 6,
    maxEventsPerSection: 50000
  },
  {
    title: "Radio Polymetric 20 Meter Demo",
    basename: "radio-polymetric-20-meter-demo",
    state: createInitialState({
      seed: "radio-20-meter-demo",
      patternCount: 20,
      startOnlyCount: 20,
      pulseCount: 0,
      meterStart: 1,
      meterCount: 20,
      baseBpm: 120,
      baseMeter: 1,
      cycleLengthKind: "resolving-sequences",
      cycleLength: 3,
      basisPolicy: "next",
      replacementCadence: "one-per-bar",
      meterTiming: "same-pulse-polymeter"
    }),
    sections: 1,
    maxEventsPerSection: 50000
  }
];

for (const demo of demos) {
  const rendered = renderArrangement(demo.state, {
    sectionCount: demo.sections,
    ppq: 480,
    maxEventsPerSection: demo.maxEventsPerSection
  });
  const midi = encodeMidiFile(rendered);
  const kitSummary = Array.from(new Set(demo.state.voices.map((voice) => voice.kit))).sort();
  const roleSummary = demo.state.voices.reduce((acc, voice) => {
    acc[voice.role] = (acc[voice.role] ?? 0) + 1;
    return acc;
  }, { "start-only": 0, pulse: 0, binary: 0 });
  const meterSummary = demo.state.voices.map((voice) => voice.meter).join(",");
  await writeFile(join(artifactDir, `${demo.basename}.mid`), midi);
  await writeFile(
    join(artifactDir, `${demo.basename}-manifest.md`),
    [
      `# ${demo.title}`,
      "",
      "Generated by `scripts/generate-demo.mjs`.",
      "",
      `MIDI: ${demo.basename}.mid`,
      `MIDI bytes: ${midi.byteLength}`,
      `Events: ${rendered.events.length}`,
      `Sections: ${rendered.sections.length}`,
      `Voices: ${demo.state.voices.length}`,
      `Roles: start-only ${roleSummary["start-only"]}; pulse ${roleSummary.pulse}; binary ${roleSummary.binary}`,
      `Meters: ${meterSummary}`,
      `Kits: ${kitSummary.join(", ")}`,
      `Cycle: ${demo.state.config.cycleLength} ${demo.state.config.cycleLengthKind}`,
      `Basis policy: ${demo.state.config.basisPolicy === "farthest" ? "farmost" : demo.state.config.basisPolicy}`,
      "",
      "Section tempo bases:",
      "",
      ...rendered.sections.map((section) => {
        return `- section ${section.sectionIndex}: ${section.baseBpm.toFixed(6)} BPM, meter ${section.baseMeter}, base voice ${section.baseVoiceId}`;
      }),
      ""
    ].join("\n"),
    "utf8"
  );
  console.log(join(artifactDir, `${demo.basename}.mid`));
}
