import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { createInitialState, renderArrangement } from "../web/lib/engine.mjs";
import { encodeMidiFile } from "../web/lib/midi-file.mjs";

const artifactDir = process.argv[2] ?? "C:\\Users\\j\\Dropbox\\Musica\\radio\\polymetric-polymodulation";

const state = createInitialState({
  seed: "radio-demo",
  patternCount: 8,
  startOnlyCount: 2,
  pulseCount: 2,
  meterStart: 1,
  meterCount: 8,
  baseBpm: 127,
  baseMeter: 1,
  cycleLengthKind: "bars",
  cycleLength: 4,
  basisPolicy: "next",
  replacementCadence: "immediate",
  meterTiming: "shared-bar-polyrhythm"
});

const rendered = renderArrangement(state, { sectionCount: 6, ppq: 480 });
const midi = encodeMidiFile(rendered);

await mkdir(artifactDir, { recursive: true });
await writeFile(join(artifactDir, "radio-polymetric-demo.mid"), midi);
await writeFile(
  join(artifactDir, "radio-polymetric-demo-manifest.md"),
  [
    "# Radio Polymetric Demo",
    "",
    "Generated by `C:\\git\\radio\\scripts\\generate-demo.mjs`.",
    "",
    `MIDI bytes: ${midi.byteLength}`,
    `Sections: ${rendered.sections.length}`,
    "",
    "Section tempo bases:",
    "",
    ...rendered.sections.map((section) => {
      return `- section ${section.sectionIndex}: ${section.baseBpm.toFixed(6)} BPM, meter ${section.baseMeter}, base voice ${section.baseVoiceId}`;
    }),
    ""
  ].join("\n"),
  "utf8"
);

console.log(join(artifactDir, "radio-polymetric-demo.mid"));
